version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: monthly
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly