# Dart analyzer configuration for Mosquito Alert Mobile App
# This file defines static analysis rules to maintain code quality

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error Prevention
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - throw_in_finally
    - unnecessary_statements
    - valid_regexps

    # Style
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls  # Catches async forEach anti-pattern
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - library_names
    - library_prefixes
    - null_closures
    - package_prefixed_library_names
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible

analyzer:
  errors:
    # Treat these as errors
    missing_required_param: error
    missing_return: error
    
    # Warnings
    avoid_print: warning
    avoid_function_literals_in_foreach_calls: warning
    
    # Info
    todo: info
    
  exclude:
    # Generated files
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    
    # Build output
    - 'build/**'
    
    # Platform specific
    - 'android/**'
    - 'ios/**'
    - 'macos/**'
    - 'linux/**'
    - 'windows/**'
    - 'web/**'
    
    # External
    - 'lib/generated/**'
