// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mosquito_alert_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BiteReportAdapter());
    registerAdapter(BreedingSiteReportAdapter());
    registerAdapter(LocalPhotoAdapter());
    registerAdapter(MemoryPhotoAdapter());
    registerAdapter(ObservationReportAdapter());
    registerAdapter(OutBoxOperationAdapter());
    registerAdapter(OutboxItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BiteReportAdapter());
    registerAdapter(BreedingSiteReportAdapter());
    registerAdapter(LocalPhotoAdapter());
    registerAdapter(MemoryPhotoAdapter());
    registerAdapter(ObservationReportAdapter());
    registerAdapter(OutBoxOperationAdapter());
    registerAdapter(OutboxItemAdapter());
  }
}
