name: Build app
on:
  merge_group:
  pull_request:
  push:
    branches: ["main"]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: kuhnroyal/flutter-fvm-config-action/setup@v3

    - name: Get Dependencies
      run: flutter pub get
    
    - name: Validate pubspec.lock is up to date
      run: |
        if ! git diff --quiet pubspec.lock; then
          echo "::error ::pubspec.lock is out of date. Run 'fvm flutter pub get' and commit the updated file."
          exit 1
        fi

    - name: Decode google-services.json
      run: echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_ANDROID_BASE64 }}

    - name: Build Android on debug mode
      run: flutter build appbundle --debug

  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: kuhnroyal/flutter-fvm-config-action/setup@v3

    - name: Decode GoogleService-Info.plist secrets
      env:
        GOOGLESERVICES_INFO_PLIST_JSON: ${{ secrets.GOOGLESERVICE_INFO_PLIST_IOS_BASE64 }}
      run: |
        echo $GOOGLESERVICES_INFO_PLIST_JSON | base64 --decode > ios/Runner/GoogleService-Info.plist

    - run: flutter pub get

    - name: Build ios
      run: flutter build ios --release --no-codesign
