name: Build app
on:
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.19.5'
    
    - name: Build appbundle
      run: flutter build appbundle --stacktrace

  ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.19.5'
    
    - name: Build ios
      run: flutter build ios --release --no-codesign
