name: Build app
on:
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.27.3'
  
    - run: flutter pub get

    - name: Build appbundle (with decoded google-services.json)
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
        flutter build appbundle --debug

  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.27.3'

    - run: flutter pub get

    - name: Build ios
      run: flutter build ios --release --no-codesign
