name: Build app
on:
  pull_request:

jobs:
  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.27.3'

    - run: flutter pub get

    - name: Build ios
      run: flutter build ios --release --no-codesign
