# TODO: Enable this. I disabled only during this task
#name: On push workflows

#on:
#  push:

#jobs:
  
#  unit_tests:
#    uses: ./.github/workflows/unit_tests.yml


  #static_analysis:
  #  uses: ./.github/workflows/static_analysis.yml