name: Static analysis
on:
  pull_request:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.0.0'   

    - name: Statically analyze the Dart code for any errors/warnings, ignoring "info" level warnings
      run: |
        if flutter analyze 2>&1 | grep -q -E 'error:|warning:'; 
        then exit 1
        else exit 0
        fi
