name: Unit tests
on: 
  workflow_call:

jobs:

  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Set up Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        dart-sdk: '2.17.6'

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.0.5'   

    - name: Get flutter dependencies
      run: flutter pub get

    - name: Run tests for our flutter project.
      run: flutter test unit_test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true