name: Update Locales

on:
    workflow_dispatch:
    push:
        tags:
            - '*'

permissions:
    contents: write
    pull-requests: write

jobs:
    sync_localise:
        uses: ./.github/workflows/sync_tags_localise.yml 
        secrets: inherit  # pass all secrets

    update-locales:
        needs: [sync_localise]  # require sync_localise to pass before deploy runs
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install requests

            - name: Run update_locales.py
              run: python update_locales.py --api_key ${{ secrets.LOCALISE_EXPORT_API_KEY }} --tags ${{ github.ref_name }}

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v7
              with:
                add-paths: |
                    assets/language/*
                commit-message: Automatic locales update for tag ${{ github.ref_name }}
                branch: i18n/update_${{ github.ref_name }}
                branch-suffix: timestamp
                delete-branch: true
                base: main
                title: '[${{ github.ref_name }}] Update locales'
                body: |
                    Changes auto-generated by [update_locales workflow][1]

                    [1]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
                labels: |
                    i18n
                draft: false
